SLACK_API_TOKEN: "xoxb-461156293569-2734098477619-jP73SZHVfnN5Lm2eFjlvxqhZ"

IBM_API_TOKEN: "0dOsyBpI4ES0krYxqy0obUkqd2dNc9f4J5T_n1NEAy6K"

TWILIO_FROM_PHONE: "+18106424186"
TWILIO_TO_PHONE: ""
TWILIO_ACCOUNT_SID: "AC56e966e36eac5a1ec1853dfe3f7344cb"
TWILIO_AUTH_TOKEN: "ec1b5e4946e740eefcc4a5e6a0b4c2aa"

POSTGRESQL_DATABASE_HOST: "codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com"
POSTGRESQL_DATABASE_DBNAME: "LEVY_POSTGRES"
POSTGRESQL_DATABASE_USER: "codeboxx"
POSTGRESQL_DATABASE_PASSWORD: "Codeboxx1!"